/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef OPENGL_JNI_NATIVES_H
#define OPENGL_JNI_NATIVES_H


#include <jni.h>

/* Header for class opengl_jni_Natives */

#ifdef __cplusplus
extern "C" {
#endif



/*
 * Class:     opengl_jni_Natives
 * Method:    NativeRender
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_opengl_jni_Natives_NativeRender
 // (JNIEnv *, jclass);

/*
 * Class:     opengl_jni_Natives
 * Method:    NativeInit
 * Signature: (Landroid/content/res/AssetManager;)V
 */
//JNIEXPORT void JNICALL Java_opengl_jni_Natives_NativeInit
 // (JNIEnv *, jclass, jobject);
//class opengl_jni_Natives


JNIEXPORT jint JNICALL Java_com_example_philipp_myapplication_Natives_NativeRender
  (JNIEnv *, jclass);

/*
 * Class:     com_example_philipp_myapplication_Natives
 * Method:    NativeInit
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_com_example_philipp_myapplication_Natives_NativeInit
  (JNIEnv *, jclass, jobject);





#ifdef __cplusplus
}
#endif
#endif


